version: '2.2'

# docker volume create --name pgdata

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 1024m
    memswap_limit: 1024m
    mem_reservation: 512m
    cpu_percent: 25
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 5050:8080
    mem_limit: 256m
    memswap_limit: 512m
    mem_reservation: 256m
    cpu_percent: 25
    restart: always
volumes:
  pgdata:
    external: true